# Generated by Django 5.2.7 on 2025-10-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('rank', models.CharField(max_length=100, verbose_name='Звання')),
                ('full_name', models.CharField(max_length=255, verbose_name='П.І.Б.')),
                ('weapon_number', models.CharField(blank=True, max_length=50, verbose_name='Номер зброї')),
                ('assistant_info', models.CharField(blank=True, max_length=255, verbose_name='Помічник ЧІ')),
                ('ppo_assistant_info', models.CharField(blank=True, max_length=255, verbose_name='Помічник ЧІ (ППО)')),
            ],
        ),
    ]
